package teammates.ui.servlets;

import java.io.IOException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.http.HttpStatus;
import teammates.common.util.Config;
import teammates.common.util.Const;
import teammates.common.util.Logger;
@Deprecated
public class LegacyUrlMapper extends HttpServlet {
private static final Logger log = Logger.getLogger();

@Override
public  void doGet(HttpServletRequest req, HttpServletResponse resp)throws IOException {
cipm.consistency.bridge.monitoring.controller.ThreadMonitoringController threadMonitoringController = cipm.consistency.bridge.monitoring.controller.ThreadMonitoringController.getInstance();
cipm.consistency.bridge.monitoring.controller.ServiceParameters monitoringServiceParameters = new  cipm.consistency.bridge.monitoring.controller.ServiceParameters();
monitoringServiceParameters.addValue("req", req);
monitoringServiceParameters.addValue("resp", resp);
threadMonitoringController.enterService("_gUhzwLvVEeyr6avTgCRLkQ", this, monitoringServiceParameters);
try {
threadMonitoringController.enterInternalAction("_gUleILvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
String uri = req.getRequestURI();
if (uri.contains(";"))
{
uri = uri.split(";")[0];
}
String baseRedirectUrl;
String redirectUrl;
String key;
String courseId;
String fsName;
switch (uri) {
case Const.LegacyURIs.INSTRUCTOR_COURSE_JOIN: threadMonitoringController.enterInternalAction("_gU_t1LvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.JOIN_PAGE;
threadMonitoringController.exitInternalAction("_gU_t1LvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
key = req.getParameter(Const.ParamsNames.REGKEY);
threadMonitoringController.setExternalCallId("_gU_t1bvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVAU4LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVA78LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVBjALvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVBjAbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVCKELvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVCxILvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVDYMLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVD_QLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVD_QbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVEmULvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVFNYLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVFNYbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVF0cLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVGbgLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVHCkLvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.JOIN_PAGE).withRegistrationKey(key).withEntityType(Const.EntityType.INSTRUCTOR).toString();
break;
case Const.LegacyURIs.STUDENT_COURSE_JOIN: case Const.LegacyURIs.STUDENT_COURSE_JOIN_NEW: threadMonitoringController.enterInternalAction("_gVHppLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
threadMonitoringController.enterInternalAction("_gVO-ZLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.JOIN_PAGE;
threadMonitoringController.exitInternalAction("_gVO-ZLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
threadMonitoringController.exitInternalAction("_gVHppLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
key = req.getParameter(Const.ParamsNames.REGKEY);
threadMonitoringController.setExternalCallId("_gVHppbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVIQsLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVIQsbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVI3wLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVJe0LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVKF4LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVKF4bvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVKs8LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVLUALvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVLUAbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVL7ELvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVMiILvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVNJMLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVNJMbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVNwQLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVOXULvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVO-ZbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVPlcLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVQMgLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVQMgbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVQzkLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVRaoLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVSBsLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVSBsbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVSowLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVTP0LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVTP0bvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVT24LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVUd8LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVVFALvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVVFAbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVVsELvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.JOIN_PAGE).withRegistrationKey(key).withEntityType(Const.EntityType.STUDENT).toString();
break;
case Const.LegacyURIs.STUDENT_HOME_PAGE: threadMonitoringController.enterInternalAction("_gVWTJLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.STUDENT_HOME_PAGE;
threadMonitoringController.exitInternalAction("_gVWTJLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
threadMonitoringController.setExternalCallId("_gVWTJbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVW6MLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVXhQLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVYIULvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.STUDENT_HOME_PAGE).toString();
break;
case Const.LegacyURIs.INSTRUCTOR_HOME_PAGE: threadMonitoringController.enterInternalAction("_gVYvYLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.INSTRUCTOR_HOME_PAGE;
threadMonitoringController.exitInternalAction("_gVYvYLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
threadMonitoringController.setExternalCallId("_gVYvYbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVYvYrvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVZWcLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVZ9gLvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.INSTRUCTOR_HOME_PAGE).toString();
break;
case Const.LegacyURIs.STUDENT_FEEDBACK_SUBMISSION_EDIT_PAGE: threadMonitoringController.enterInternalAction("_gVbLpLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.SESSION_SUBMISSION_PAGE;
threadMonitoringController.exitInternalAction("_gVbLpLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
key = req.getParameter(Const.ParamsNames.REGKEY);
courseId = req.getParameter(Const.ParamsNames.COURSE_ID);
fsName = req.getParameter(Const.ParamsNames.FEEDBACK_SESSION_NAME);
threadMonitoringController.setExternalCallId("_gVbLpbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVcZwLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVcZwbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVdA0LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVdn4LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVeO8LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVe2ALvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVfdELvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVgEILvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVgrMLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVh5ULvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVigYLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVjHcLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVjugLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVkVkLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVk8oLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVljsLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVmKwLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVmx0LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVnY4LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVn_8LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVonALvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVpOELvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVpOEbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVqcMLvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.SESSION_SUBMISSION_PAGE).withRegistrationKey(key).withCourseId(courseId).withSessionName(fsName).toString();
break;
case Const.LegacyURIs.INSTRUCTOR_FEEDBACK_SUBMISSION_EDIT_PAGE: threadMonitoringController.enterInternalAction("_gVqcNbvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.INSTRUCTOR_SESSION_SUBMISSION_PAGE;
threadMonitoringController.exitInternalAction("_gVqcNbvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
courseId = req.getParameter(Const.ParamsNames.COURSE_ID);
fsName = req.getParameter(Const.ParamsNames.FEEDBACK_SESSION_NAME);
threadMonitoringController.setExternalCallId("_gVqcNrvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVrqULvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVrqUbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVsRYLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVs4cLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVtfgLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVuGkLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVutoLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVvUsLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVvUsbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVv7wLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVwi0LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVwi0bvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVxJ4LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVxw8LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVyYALvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.INSTRUCTOR_SESSION_SUBMISSION_PAGE).withCourseId(courseId).withSessionName(fsName).toString();
break;
case Const.LegacyURIs.STUDENT_FEEDBACK_RESULTS_PAGE: threadMonitoringController.enterInternalAction("_gVy_ELvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.SESSION_RESULTS_PAGE;
threadMonitoringController.exitInternalAction("_gVy_ELvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
key = req.getParameter(Const.ParamsNames.REGKEY);
courseId = req.getParameter(Const.ParamsNames.COURSE_ID);
fsName = req.getParameter(Const.ParamsNames.FEEDBACK_SESSION_NAME);
threadMonitoringController.setExternalCallId("_gVy_EbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVy_ErvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gVzmILvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV0NMLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV00QLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV00QbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV1bULvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV2CYLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV2pcLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV3QgLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV33kLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV4eoLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV5FsLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV5swLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV6T0LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV664LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV7h8LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV8JALvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV8wELvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV9XILvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV-lQLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV_MULvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gV_zYLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWBBgLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWC2sLvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.SESSION_RESULTS_PAGE).withRegistrationKey(key).withCourseId(courseId).withSessionName(fsName).toString();
break;
case Const.LegacyURIs.INSTRUCTOR_FEEDBACK_RESULTS_PAGE: threadMonitoringController.enterInternalAction("_gWEE1LvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = Const.WebPageURIs.INSTRUCTOR_SESSION_RESULTS_PAGE;
threadMonitoringController.exitInternalAction("_gWEE1LvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
courseId = req.getParameter(Const.ParamsNames.COURSE_ID);
fsName = req.getParameter(Const.ParamsNames.FEEDBACK_SESSION_NAME);
threadMonitoringController.setExternalCallId("_gWEE1bvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWEr4LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWFS8LvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWFS8bvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWF6ALvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWGhELvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWHIILvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWHIIbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWHvMLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWIWQLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWIWQbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWI9ULvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWJkYLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWJkYbvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWKygLvVEeyr6avTgCRLkQ");
threadMonitoringController.setExternalCallId("_gWLZkLvVEeyr6avTgCRLkQ");
redirectUrl = Config.getFrontEndAppUrl(Const.WebPageURIs.INSTRUCTOR_SESSION_RESULTS_PAGE).withCourseId(courseId).withSessionName(fsName).toString();
break;
default: threadMonitoringController.enterInternalAction("_gWMApLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
baseRedirectUrl = "/";
threadMonitoringController.exitInternalAction("_gWMApLvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
redirectUrl = "/";
threadMonitoringController.setExternalCallId("_gWMApbvVEeyr6avTgCRLkQ");
log.warning("Unmapped legacy URL: " + uri);
break;

}
log.request(req, HttpStatus.SC_MOVED_PERMANENTLY, "Redirect legacy URL from " + uri + " to " + baseRedirectUrl);
resp.sendRedirect(redirectUrl);
threadMonitoringController.exitInternalAction("_gUleILvVEeyr6avTgCRLkQ", "_oro4gG3fEdy4YaaT-RYrLQ");
}
finally {
threadMonitoringController.exitService("_gUhzwLvVEeyr6avTgCRLkQ");
}
}

}
